// AUTO-GENERATED by scripts/bake-data.js — do not edit manually
export const OUTPUT_DATA = {
  "security_report": null,
  "opa_cis_result": null,
  "opa_vm_result": null,
  "opa_tags_result": null,
  "compliance_dashboard_latest": null,
  "compliance_dashboard_pre_remediation": null,
  "compliance_dashboard_post_remediation": null,
  "nsg_drift": null,
  "storage_drift": null,
  "scaling_drift": null,
  "iam_drift": null,
  "nsg_raw": null,
  "storage_raw": null,
  "scaling_raw": null,
  "iam_raw": null
};
