/**
 * Reads every JSON file from the pipeline output folders and writes
 * src/generatedData.js so the React app has all data baked into the bundle.
 *
 * Source priority (first match wins per file):
 *   1. Pipeline1 workspace outputs/
 *   2. Pipeline2 workspace outputs/
 *   3. Repo-local outputs/  (fallback when running in the same workspace)
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DASHBOARD_ROOT = resolve(__dirname, '..');
const REPO_ROOT      = resolve(DASHBOARD_ROOT, '..');

const SOURCE_DIRS = [
  'C:/ProgramData/Jenkins/.jenkins/workspace/Bharath_C1_Pipeline1/outputs',
  'C:/ProgramData/Jenkins/.jenkins/workspace/Bharath_C1_Pipeline2/outputs',
  join(REPO_ROOT, 'outputs'),          // local fallback
  join(DASHBOARD_ROOT, 'public', 'outputs'), // last resort
];

const FILE_KEYS = [
  'security_report',
  'opa_cis_result',
  'opa_vm_result',
  'opa_tags_result',
  'compliance_dashboard_latest',
  'compliance_dashboard_pre_remediation',
  'compliance_dashboard_post_remediation',
  'nsg_drift',
  'storage_drift',
  'scaling_drift',
  'iam_drift',
  'nsg_raw',
  'storage_raw',
  'scaling_raw',
  'iam_raw',
];

console.log('\n========================================');
console.log(' bake-data.js — scanning source folders');
console.log('========================================');

// Report which source dirs exist
SOURCE_DIRS.forEach(d => {
  console.log(existsSync(d) ? ` [EXISTS] ${d}` : ` [MISS  ] ${d}`);
});
console.log('');

const result = {};
let loadedCount = 0;

for (const key of FILE_KEYS) {
  const filename = `${key}.json`;
  let loaded = false;

  for (const dir of SOURCE_DIRS) {
    const fullPath = join(dir, filename);
    if (existsSync(fullPath)) {
      try {
        result[key] = JSON.parse(readFileSync(fullPath, 'utf8'));
        console.log(` [OK   ] ${key}.json  ←  ${fullPath}`);
        loaded = true;
        loadedCount++;
        break;
      } catch (e) {
        console.warn(` [ERR  ] ${key}.json parse error: ${e.message}`);
      }
    }
  }

  if (!loaded) {
    result[key] = null;
    console.warn(` [MISS ] ${key}.json  — not found in any source`);
  }
}

const outPath = join(DASHBOARD_ROOT, 'src', 'generatedData.js');
writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/bake-data.js — do not edit manually\nexport const OUTPUT_DATA = ${JSON.stringify(result, null, 2)};\n`,
  'utf8'
);

console.log(`\n✓ Wrote ${outPath}`);
console.log(`  ${loadedCount}/${FILE_KEYS.length} files loaded\n`);

if (loadedCount === 0) {
  console.warn('WARNING: No JSON files found. Run Pipeline1 and Pipeline2 first.');
}
